apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.Name }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Values.Name }}

  template:
    metadata:
      labels:
        app: {{ .Values.Name }}

    spec:
      containers:
        - name: {{ .Values.Name }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          resources:
{{ toYaml .Values.resources | indent 12 }}
