name: whoami-test

replicaCount: 1

image:
  repository: traefik/whoami
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: whoami-test
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: whoami-test.local
  path: /

nodeSelector: {}

tolerations: []

affinity: {}

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
